version: '2'
services:
    jhipster-postgresql:
        container_name: jhipster-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/jhipster/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=jhipster
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
